name: Deploy GitHub Pages

# Trigger the workflow on commits to the 'main' branch
on:
  push:
    branches:
      - main

# Define the job to build and deploy the site
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (adjust the version as needed for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          ng build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Replace with the directory containing your built files
